this._yttv=this._yttv||{};(function(_){var window=this;
try{
_.p("DwcTwf");
var GUa=_.x("SignInWithAccountManagerService","DwcTwf");var HUa;
HUa=class{constructor(){this.A=_.B.get(_.Fn);this.j=_.B.get(_.Vp);this.Yf=_.B.get(_.Kk);this.accountManager=_.B.get(_.Tp)}signIn(a,b){const c=!!_.Aj().authConfig.enableAccountManagerAccountPropagation,d=_.A("enableLateDelegationForAccountManager",!1),e=Object.assign({},_.yy,{enableAmatiDeviceGetToken:c,enableKimonoBrandAccountPicker:!d});return _.ye(this.accountManager.requestPairing(e)).pipe(_.cf(({token:f,expiry:g})=>f?this.j.A({},f,{Rm:!0,accountReadMask:{returnOwner:!0,returnBrandAccounts:d,returnPersonaAccounts:!!_.A("kidsExperienceConfig",
{}).gu,returnFamilyChildAccounts:!!_.A("kidsExperienceConfig",{}).dz,returnFamilyMembersAccounts:_.Np()}}).pipe(_.Ne(h=>{if(c||d){var k;let m,n;const q=(k=h.values().next())==null?void 0:(m=k.value)==null?void 0:(n=m.identity)==null?void 0:n.ownerObfuscatedGaiaId;k=_.Gp();delete k[q];_.B.get(_.Hn).set(_.Kp,k)}return{qe:h,accessToken:f,durationSec:g}})):_.jw),_.Ne(f=>{var g=f.qe.values().next().value.identity.ownerObfuscatedGaiaId;g=f.qe.get(g);if(!g)throw Error("We");g=g.identity;this.A.Jk(g,{},{eventTrigger:a,
signInMethod:b});g=_.Dj(f.accessToken,f.durationSec,g);_.Jk(this.Yf,_.vy);_.Yy(this.Yf,g);return f.qe}),_.Ye())}};_.IUa=_.R(GUa,()=>new HUa);
_.r();
}catch(e){_._DumpException(e)}
try{
_.yUa=new _.O("messageThumbnailRenderer");
}catch(e){_._DumpException(e)}
try{
_.JH=function(a){const b=_.A("isRtl",!1)?"_rtl":"";return _.xq(`${a}${b}.png`)};
}catch(e){_._DumpException(e)}
try{
var EUa,OH;
_.FUa=function(a,b,c,d,e){var f={title:{simpleText:_.H("SIGN_IN_GOOGLE_ACCOUNT_TITLE")}};a.eventTrigger==="ACCOUNT_EVENT_TRIGGER_VISITOR_SUSPICIOUS_REQUEST"?f.title={simpleText:_.H("SIGN_IN_TEXT_SUSPICIOUS_REQUEST")}:f.image={thumbnails:[{url:_.xq("sign-in-promo.png"),width:346,height:234}]};var g=a.eventTrigger&&_.Iq[a.eventTrigger];g&&(f.subtitle={simpleText:_.H(g)});OH=(0,_.JHa)();f={header:{overlayPanelHeaderRenderer:f},themeStyle:"KABUKI_THEME_STYLE_PLATFORM"};g=_.zq("SIGN_IN_METHOD_TYPE_DIRECT");e?
f.content={overlayPanelItemListRenderer:{items:EUa(e)}}:g&&!d?(d=[{compactLinkRenderer:{la:(0,_.qoa)(OH),title:{simpleText:_.H("SIGNIN_DIRECT")},serviceEndpoint:_.rq(a,{signInType:"SIGN_IN_METHOD_TYPE_DIRECT",signInStyle:c})}}],_.A("mdxConfig",_.$o).supportsSeamlessSignIn?d.push({compactLinkRenderer:{la:(0,_.moa)(OH),title:{simpleText:_.H("SIGNIN_WITH_PHONE")},serviceEndpoint:_.rq(a,{signInType:"SIGN_IN_METHOD_TYPE_SEAMLESS",signInStyle:c})}}):d.push({compactLinkRenderer:{la:(0,_.noa)(OH),title:{simpleText:_.H("SIGNIN_URL")},
serviceEndpoint:_.rq(a,{signInType:"SIGN_IN_METHOD_TYPE_URL",signInStyle:c})}}),f.footer={overlayPanelItemListRenderer:{items:d}}):f.content={overlayPanelItemListRenderer:{items:EUa(_.rq(a,{signInStyle:c,signInType:d}))}};return _.Wn({la:OH,overlayPanelRenderer:f,dismissalCommand:b,uniqueId:"sign-in-interstitial-overlay",updateAction:!0})};EUa=function(a){return[{compactLinkRenderer:{la:(0,_.ct)(OH),title:{simpleText:_.H("SIGN_IN_TEXT")},serviceEndpoint:a}}]};
}catch(e){_._DumpException(e)}
try{
var LUa=function(a=_.JC){var b=window.location;_.t(function*(){var c=_.Aj(),d=_.wk(),e=_.Xh(),f=c.clientLanguage,g=_.eq("oxbow_exceptions_sw",0),h=_.A("isCobaltHybridNav",!1),k=_.A("enableClientNav",!1),m=_.B.get(_.IH),n=_.A("directSignInConfig",_.doa);d=(new JUa).setVisitorData(d);d=_.Mu(d,6,_.$h());e=_.Ku(d,7,e);d=KUa();e=_.Mu(e,4,d);f=_.Mu(e,9,f);g=_.Ku(f,10,g);g=_.uu(g,11,_.cc(!0));g=_.Mu(g,12,c.forceScreenReaderMode);h=_.uu(g,13,_.cc(h));k=_.uu(h,18,_.cc(k));k=_.Ou(k,14,1);h=_.A("isRtl",!1);
k=_.uu(k,15,_.cc(h));m=m.mode===3;if(n.enableDebugParameters||m)_.uu(k,8,_.cc(!0)),n=_.ck(b,"oxredir").toString()||null,_.Mu(k,5,n);c=c.oAuthClientProfiles[1];n=_.Mw(c.wI);m=new _.Xj(b.href);for(var q of _.kz.concat(_.CBa))_.Qk(m.j,q)&&_.xp(n,q,m.j.Ac(q));_.Mu(k,2,n.toString());q=!!_.ck(b,"env_useGaiaSandbox");q=_.ck(b,"env_useGaiaStaging")?_.Mw("https://gaiastaging.corp.google.com/o/oauth2/cl"):q?_.Mw("https://accounts.sandbox.google.com/o/oauth2/cl"):_.Mw("https://accounts.google.com/o/oauth2/cl");
_.yp(q,"signin_state",k.serialize());_.yp(q,"redirect_uri","urn:ietf:wg:oauth:2.0:oob:auto");_.yp(q,"client_id",c.clientId);_.yp(q,"scope",c.scopes);_.yp(q,"response_type","code");_.yp(q,"access_type","offline");c=_.yj();_.yp(q,"device_id",_.XF());_.yp(q,"device_model",`ytlr:${c.brand}:${c.model}`.toLowerCase());yield _.$s({event_type:4});_.rh();_.gJa(a);_.zk(b,q.toString())})},KUa=function(){const a=_.Aj(),b=new Set(MUa),c=_.Uba(_.yj(),(e,f)=>b.has(f));let d;c.browser_engine=(d=window.environment)==
null?void 0:d.browser_engine;c.client_name=a.clientName;c.client_version=a.clientVersion;return JSON.stringify(c)},OUa=function(a,b){var c=b==="SIGN_IN_STYLE_VERIFY_ITS_YOU_FULLSCREEN"?_.co({title:_.H("VERIFY_ITS_YOU_OVERLAY_TITLE"),subtitle:_.H("VERIFY_ITS_YOU_OVERLAY_SUBTITLE")}):b==="SIGN_IN_STYLE_SIDE_PANEL"?_.co({title:_.H("SEAMLESS_OVERLAY_TITLE"),image:{thumbnails:[{height:216,url:_.xq("sign_in_tap_account_2.png"),width:216}]}}):_.co({title:_.H("SEAMLESS_OVERLAY_TITLE")});const d={width:80,
height:45,thumbnailDetails:{thumbnails:[{url:_.xq(_.A("isRtl",!1)?"sign-in-seamless-background-2-rtl.png":"sign-in-seamless-background-2.png"),width:1280,height:720}]}};QH=(0,_.KHa)();const e=_.vq(_.wq("CANCELLED","SIGN_IN_METHOD_TYPE_SEAMLESS",a==null?void 0:a.eventTrigger,void 0,"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_USER_CANCELED"));var f=QH;c={overlayPanelHeaderRenderer:c};var g={seamlessSignInRenderer:{identityActionContext:a}},h;let k;const m={commandExecutorCommand:{commands:[_.wq("CANCELLED",
"SIGN_IN_METHOD_TYPE_SEAMLESS",(h=a)==null?void 0:h.eventTrigger,void 0,"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_ALTERNATIVE_METHOD_SELECTED"),((k=a)==null?void 0:k.nextEndpoint)||{}]}};a=Object.assign({},a,{nextEndpoint:m});h=[{compactLinkRenderer:{la:(0,_.Coa)(QH),title:{runs:[{text:_.H("TRY_ANOTHER_WAY")}]},serviceEndpoint:_.rq(a||{},{signInType:"SIGN_IN_METHOD_TYPE_URL",signInStyle:b})}}];return _.Wn({uniqueId:"seamless-sign-in",la:f,overlayPanelRenderer:{header:c,content:g,footer:{overlayPanelItemListRenderer:{items:h}},
themeStyle:"KABUKI_THEME_STYLE_PLATFORM"},contextualPanelRenderer:NUa.includes(b)?{messageThumbnailRenderer:d}:void 0,dismissalCommand:e})},QUa=function(a,b){var c=b==="SIGN_IN_STYLE_VERIFY_ITS_YOU_FULLSCREEN"?_.co({title:_.H("VERIFY_ITS_YOU_OVERLAY_TITLE"),subtitle:_.H("VERIFY_ITS_YOU_OVERLAY_SUBTITLE")}):b==="SIGN_IN_STYLE_SIDE_PANEL"?_.co({title:_.H("SIGNIN_WITH_PHONE"),image:{thumbnails:[{height:216,url:_.xq("browser-youtube.png"),width:216}]}}):_.co({title:_.H("SIGNIN_WITH_PHONE")});const d=
{width:80,height:45,thumbnailDetails:{thumbnails:[{url:_.xq(_.A("isRtl",!1)?"sign-in-ctx-panel-720p-browser-rtl.png":"sign-in-ctx-panel-720p-browser.png"),width:1280,height:720}]}};PUa=(0,_.ooa)();const e=_.vq(_.wq("CANCELLED","SIGN_IN_METHOD_TYPE_URL",a==null?void 0:a.eventTrigger,void 0,"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_USER_CANCELED"));return _.Wn({uniqueId:"url-sign-in-overlay",la:PUa,overlayPanelRenderer:{header:{overlayPanelHeaderRenderer:c},content:{urlSignInRenderer:{identityActionContext:a}},
themeStyle:"KABUKI_THEME_STYLE_PLATFORM"},contextualPanelRenderer:NUa.includes(b)?{messageThumbnailRenderer:d}:void 0,dismissalCommand:e})},TUa=function(a){_.t(function*(){_.kRa();const b=_.D();var c=yield RUa();c=SUa(a,c);return b.resolveCommand(c)})},SUa=function(a,b=!1){var c=_.A("enablePrismaOnboardingUiChanges",!1)?"PARENTS_SIGN_IN_TO_ADD_KID_ACCOUNT_TITLE":"CREATE_YTK_PROFILE_TITLE",d=_.A("enablePrismaOnboardingUiChanges",!1)?"PARENTS_SIGN_IN_TO_ADD_KID_ACCOUNT_NO_CTA_PAGE_SUBTITLE":"CREATE_YTK_PROFILE_SUBTITLE";
if((a==null?0:a.eventTrigger)&&(!_.A("enablePrismaOnboardingUiChanges",!1)||(a==null?void 0:a.eventTrigger)!=="ACCOUNT_EVENT_TRIGGER_YTK_ONBOARDING")){var e=UUa[a==null?void 0:a.eventTrigger],f=VUa[a==null?void 0:a.eventTrigger];c=e!=null?e:c;d=f!=null?f:d}a=Object.assign({},a,{eventTrigger:"ACCOUNT_EVENT_TRIGGER_YTK_ONBOARDING",secondScreenRedirectUrl:"https://families.youtube.com?flow=KIDS_FLOW_TYPE_PARENT_TOOLS_PROFILE_CREATION&host_name=HOST_CLIENT_NAME_LIVING_ROOM_KIDS_SECONDARY_DEVICE",rapidQrFeature:"RAPID_QR_FEATURE_YTK"});
if(b){e={compactLinkRenderer:{icon:{iconType:"PHONE"},title:{runs:[{text:_.H("SIGNIN_QR_OR_URL")}]},subtitle:{runs:[{text:_.H("RECOMMENDED_SHELF_TITLE")}]},style:"COMPACT_LINK_STYLE_TYPE_TVFILM_ENTITY_PROVIDER",onFocusCommand:{commandExecutorCommand:{commands:[WUa(_.JH(_.A("enablePrismaOnboardingUiChanges",!1)?"kids/backgrounds/identity/v0/create_kid_profile_background_prisma_1280_720":"kids/backgrounds/identity/v0/create_kid_profile_background_purple_1280_720")),XUa(0)]}}}};var g;f=(g=_.pq(_.Xr(),
{veType:176502}))!=null?g:void 0;a:if(g=a.nextEndpoint,_.u(g,_.qA))var h=g;else{if(g=(h=_.u(g,_.lo))==null?void 0:h.commands)for(const m of g)if(_.u(m,_.qA)){h=m;break a}h=void 0}h={compactLinkRenderer:{la:f,icon:{iconType:"EXIT_TO_APP"},secondaryIconFocused:{iconType:"CHEVRON_RIGHT"},title:{runs:[{text:_.H(_.A("enablePrismaOnboardingUiChanges",!1)?"TRY_YOUTUBE_KIDS_SIGNED_OUT_CTA_TITLE":"CREATE_YTK_PROFILE_SET_UP_GUEST_TITLE")}]},subtitle:{runs:[{text:_.H(_.A("enablePrismaOnboardingUiChanges",!1)?
"TRY_YOUTUBE_KIDS_SIGNED_OUT_CTA_SUBTITLE":"CREATE_YTK_PROFILE_SET_UP_GUEST_SUBTITLE")}]},style:"COMPACT_LINK_STYLE_TYPE_TVFILM_ENTITY_PROVIDER",serviceEndpoint:_.Bq(YUa,ZUa(),h),onFocusCommand:{commandExecutorCommand:{commands:[WUa(_.JH(_.A("enablePrismaOnboardingUiChanges",!1)?"kids/backgrounds/identity/v0/set_up_ytk_guest_background_prisma_1920_1080":"kids/backgrounds/identity/v0/set_up_ytk_guest_background_1280_720")),XUa(1)]}}}};e=[e,h]}else e=[];c={entityMetadataRenderer:{layout:"ENTITY_METADATA_LAYOUT_ADD_ACCOUNT",
titleArt:{thumbnails:[{url:_.xq("ytk-kids-logo-v3.png"),width:20,height:2}]},title:{simpleText:_.H(c)},description:!_.A("enablePrismaOnboardingUiChanges",!1)||_.A("enablePrismaOnboardingUiChanges",!1)&&!b?{simpleText:_.H(d),rtl:_.A("isRtl",!1)}:void 0,buttons:e,selectedButtonIndex:0}};d=_.Vj()?{urlSignInRenderer:{identityActionContext:a,signInStyle:"SIGN_IN_STYLE_YTK_ONBOARDING",qrCode:{qrCodeRenderer:{spinner:{},style:"QR_CODE_RENDERER_STYLE_TWO_COLUMN"}}}}:$Ua();c={twoColumnRenderer:{style:"TWO_COLUMN_RENDERER_STYLE_ADD_ACCOUNT",
leftColumn:c,rightColumn:{entityButtonDetailsRenderer:{renderers:b?[d,{}]:[d],selectedIndex:0}},backgroundImage:{thumbnails:[{url:_.JH(_.A("enablePrismaOnboardingUiChanges",!1)?"kids/backgrounds/identity/v0/create_kid_profile_background_prisma_1280_720":"kids/backgrounds/identity/v0/create_kid_profile_background_purple_1280_720"),width:1280,height:720}]},scrimOptions:{scrimStyle:"SCRIM_STYLE_NONE"}}};d={commandExecutorCommand:{commands:[aVa,ZUa()]}};let k;b=(k=_.pq(_.Xr(),{veType:b?234409:234408}))!=
null?k:void 0;return _.Xn({overlayPanelRenderer:{content:c,themeStyle:"KABUKI_THEME_STYLE_PLATFORM"},la:b,Kg:d})},ZUa=function(){return _.wq("CANCELLED","SIGN_IN_METHOD_TYPE_URL","ACCOUNT_EVENT_TRIGGER_YTK_ONBOARDING",void 0,"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_USER_CANCELED")},$Ua=function(){const a={qrCodeRenderer:{qrCodeImage:{thumbnails:[{url:_.xq("families-youtube-kid-profile-url-qr-code.png"),width:300,height:300}]},style:"QR_CODE_RENDERER_STYLE_TWO_COLUMN"}},b=[_.bo({label:"1",style:"OVERLAY_MESSAGE_STYLE_INDENTED_NUMBERED_SENTENCE",
title:_.H("SCAN_WITH_PHONE_OR_GO_TO"),subtitle:"yt.be/kidprofile"}),_.bo({label:"2",style:"OVERLAY_MESSAGE_STYLE_INDENTED_NUMBERED_SENTENCE",title:_.H("CREATE_YTK_PROFILE_OFF_DEVICE_COMPLETE_STEPS")}),_.bo({label:"3",style:"OVERLAY_MESSAGE_STYLE_INDENTED_NUMBERED_SENTENCE",title:_.H("CREATE_YTK_PROFILE_OFF_DEVICE_RETURN")})];return{overlayPanelItemListRenderer:{items:[a,...b.map(c=>({overlayMessageRenderer:c}))]}}},WUa=function(a){return{setAppBackgroundCommand:{image:{thumbnails:[{url:a}]},scrimStyle:"SCRIM_STYLE_TVOD_TRANSPARENT_BACKGROUND"}}},
XUa=function(a){return{updateEntityButtonDetailsCommand:{selectedIndex:a}}},RUa=function(){return _.t(function*(){var {nM:a}=_.A("kidsExperienceConfig",{});if(!a||!_.Vj()||_.tk)return!1;a=yield _.B.get(_.Fn).zd();const b=_.Kq();return a&&Object.keys(a).length>=1||b?!1:!0})},hVa=function(a){const b=_.D(),c=_.B.get(_.Ps);if(bVa(a))a=_.Lq({identityActionContext:a.identityActionContext,showYtkOnboardingButton:a.showYtkOnboardingButton}),b.resolveCommand(a);else if(cVa(a))a=_.FUa(a.identityActionContext||
{},void 0,a.signInStyle),b.resolveCommand(a);else{var d=dVa(a),e,f;_.YF(c,d,(f=(e=a.identityActionContext)==null?void 0:e.eventTrigger)!=null?f:"ACCOUNT_EVENT_TRIGGER_UNKNOWN");if(eVa(a))a.isRetry&&_.Wp.getInstance().j(new _.J("retrySignIn"));else if(fVa(a))TUa(a.identityActionContext);else switch(d){case "SIGN_IN_METHOD_TYPE_NATIVE":gVa(a,d);break;case "SIGN_IN_METHOD_TYPE_DIRECT":LUa(a.identityActionContext);break;case "SIGN_IN_METHOD_TYPE_SEAMLESS":let g;((g=a.identityActionContext)==null?void 0:
g.eventTrigger)==="ACCOUNT_EVENT_TRIGGER_PASSIVE"?_.Qr(_.Rs).then(h=>{h.B().G(new _.LH({Gk:()=>{},Jm:()=>{}}))}):(a=OUa(a.identityActionContext,a.signInStyle),b.resolveCommand(a));break;default:a=QUa(a.identityActionContext,a.signInStyle),b.resolveCommand(a)}}},cVa=function(a){a=a.signInType;return(!a||a==="SIGN_IN_METHOD_TYPE_UNKNOWN")&&_.zq("SIGN_IN_METHOD_TYPE_DIRECT")},bVa=function(a){const b=a.signInType,c=a.isRetry;return a.signInStyle==="SIGN_IN_STYLE_TWO_COLUMN"&&c?!0:_.A("enableUniversalSignIn",
!1)&&(!b||b==="SIGN_IN_METHOD_TYPE_UNKNOWN")},eVa=function(a){a=a.signInStyle;return a==="SIGN_IN_STYLE_TWO_COLUMN_PAGE"||a==="SIGN_IN_STYLE_TWO_COLUMN"},fVa=function(a){const b=a.signInType;if(a.signInStyle==="SIGN_IN_STYLE_YTK_ONBOARDING"){if(b==="SIGN_IN_METHOD_TYPE_URL"||b==="SIGN_IN_METHOD_TYPE_NATIVE")return!0;_.z(Error("Xe"))}return!1},dVa=function(a){return(a=a.signInType)&&_.zq(a)?a:_.zq("SIGN_IN_METHOD_TYPE_SEAMLESS")?"SIGN_IN_METHOD_TYPE_SEAMLESS":_.zq("SIGN_IN_METHOD_TYPE_NATIVE")?"SIGN_IN_METHOD_TYPE_NATIVE":
"SIGN_IN_METHOD_TYPE_URL"},gVa=function(a,b){const c=_.B.get(_.IUa),d=_.B.get(_.Ps),e=_.B.get(_.Jn),f=_.D();let g=!0,h;c.signIn((h=a.identityActionContext)==null?void 0:h.eventTrigger,b).subscribe({next(k){g=!1;f.resolveCommand({signalAction:{signal:"CLOSE_POPUP"}});const m=_.A("enableBrandSelectorForAccountManager",!1),n=_.at(k).identity;if(k.size>1&&m){_.Lp(n.ownerObfuscatedGaiaId,n);let q;f.resolveCommand(_.ht({items:Array.from(k.values()),identityActionContext:(q=a.identityActionContext)!=null?
q:_.NH}))}else e.set(n,a.identityActionContext)},error(k){if(k instanceof _.Yp&&k.bo()===4){var m;_.Os(d,{sliStatus:"CANCELLED",cancellationType:"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_USER_CANCELED",signInMethodType:"SIGN_IN_METHOD_TYPE_NATIVE",eventTrigger:(m=a.identityActionContext)==null?void 0:m.eventTrigger});let v;((v=a.identityActionContext)==null?void 0:v.eventTrigger)==="ACCOUNT_EVENT_TRIGGER_ANDROID_SWITCH_ACCOUNTS"&&_.zp()}else{var n;m=(n=k.Xp)!=null?n:{sliStatus:"FAILURE"};var q;_.Os(d,
Object.assign({},m,{signInMethodType:"SIGN_IN_METHOD_TYPE_NATIVE",eventTrigger:(q=a.identityActionContext)==null?void 0:q.eventTrigger}));_.z(k);f.resolveCommand(_.MH({startSignInCommand:a}))}},complete(){if(g){let k;_.Os(d,{sliStatus:"CANCELLED",cancellationType:"TVHTML5_ACCOUNT_EVENT_CANCELLATION_TYPE_USER_CANCELED",signInMethodType:"SIGN_IN_METHOD_TYPE_NATIVE",eventTrigger:(k=a.identityActionContext)==null?void 0:k.eventTrigger});let m;((m=a.identityActionContext)==null?void 0:m.eventTrigger)===
"ACCOUNT_EVENT_TRIGGER_ANDROID_SWITCH_ACCOUNTS"&&_.zp()}}})},aVa={signalAction:{signal:"RESET_ACCOUNTS_LIST"}},iVa={kidsFlowEndpoint:{flowType:"KIDS_FLOW_TYPE_ONBOARDING"}},YUa={parentalGateCommand:{gateType:"PARENTAL_GATE_TYPE_AGE_GATE",onSuccessCommand:iVa,onFailureCommand:{parentalGateCommand:{gateType:"PARENTAL_GATE_TYPE_MATH_GATE",onSuccessCommand:iVa}}}},UUa={ACCOUNT_EVENT_TRIGGER_CONTENT_BLOCK:"CREATE_YTK_PROFILE_TITLE_BLOCK",ACCOUNT_EVENT_TRIGGER_SUBSCRIBE:"CREATE_YTK_PROFILE_TITLE_SUBCRIBE",
ACCOUNT_EVENT_TRIGGER_SUBSCRIBE_PROMO:"CREATE_YTK_PROFILE_TITLE_SUBCRIBE",ACCOUNT_EVENT_TRIGGER_YTK_ONBOARDING:"CREATE_YTK_PROFILE_TITLE"},VUa={ACCOUNT_EVENT_TRIGGER_CONTENT_BLOCK:"CREATE_YTK_PROFILE_SUBTITLE_SUBSCRIBE_OR_BLOCK",ACCOUNT_EVENT_TRIGGER_SUBSCRIBE:"CREATE_YTK_PROFILE_SUBTITLE_SUBSCRIBE_OR_BLOCK",ACCOUNT_EVENT_TRIGGER_SUBSCRIBE_PROMO:"CREATE_YTK_PROFILE_SUBTITLE_SUBSCRIBE_OR_BLOCK",ACCOUNT_EVENT_TRIGGER_YTK_ONBOARDING:"CREATE_YTK_PROFILE_SUBTITLE"},NUa=["SIGN_IN_STYLE_FULLSCREEN","SIGN_IN_STYLE_VERIFY_ITS_YOU_FULLSCREEN"];var JUa=class extends _.xd{constructor(a){super(a)}getVisitorData(){return _.Hu(this,1)}setVisitorData(a){return _.Mu(this,1,a)}};var MUa="brand model year platform platform_detail chipset browser browser_version network os os_version".split(" ");var QH;var PUa;var jVa=class extends _.sG{resolveCommand(a){return _.t(function*(){_.B.get(_.Ns).Ea("sign-in-started");hVa(_.u(a,_.qDa))})}};_.R(_.PH,()=>new jVa);
}catch(e){_._DumpException(e)}
try{
_.p("hfnUMe");

_.r();
}catch(e){_._DumpException(e)}
})(this._yttv);
// Google Inc.
