this._yttv=this._yttv||{};(function(_){var window=this;
try{
_.p("s8cxdd");
var X4=function(a,b){let c;return(c=a.getAttribute(b))==null?void 0:c.trim()},Y4=function(a){return a.filter(b=>b!==",").join(", ").replace("exit, dialog, entering, dialog","entering, dialog").replace("entering, dialog, entering, dialog","entering, dialog")},X3b=function(a,b){return(a=a.MutationObserver||a.WebKitMutationObserver||a.MozMutationObserver||a.OMutationObserver||a.MsMutationObserver)?new a(c=>{b(c)}):null},Y3b=function(a,b){if(a===document.activeElement){var c=document.title;document.title=
b;a.addEventListener("focusout",()=>{document.title=c},{once:!0})}},Z4=function(a){requestAnimationFrame(()=>{setTimeout(a,0)})},Z3b=function(a,b){for(;a&&!(a instanceof Element);)a=a.parentNode;a&&b.add(a)},$4=function(a,b){for(;a;){if(b.has(a))return!0;a=a.parentNode}return!1},$3b=function(a,b){return a!==b&&b&&$4(a,new Set([b]))},d4b=function(){return _.t(function*(){var a;let b;if(!(((a=window.environment)==null?void 0:(b=a.server_ua)==null?void 0:b.toLowerCase())||"").includes("tizen"))return a4b;
try{return a=[],a.push(b4b()),a.push(c4b()),yield _.Sv(a)}catch(c){return a4b}})},b4b=function(){return _.t(function*(){return new _.uh(a=>{setTimeout(()=>{a(a4b)},5E3)})})},c4b=function(){return _.t(function*(){try{const a=()=>{let c;const d=(c=window.webapis)==null?void 0:c.tvinfo;let e;return d&&d.getMenuValue&&((e=d.TvInfoMenuKey)==null?0:e.VOICE_GUIDE_KEY)?d.getMenuValue(d.TvInfoMenuKey.VOICE_GUIDE_KEY):!1},b={attributes:{nonce:window.csp_nonce||""}};yield e4b((0,_.Od)`$WEBAPIS/webapis/webapis.js`,
b);a();return a}catch(a){return b4b()}})},j4b=function(){return _.t(function*(){var a,b=((a=_.Aj().forceScreenReaderMode)==null?void 0:a.toLowerCase())||"";if(b||!window.chrome){f4b(b);var c;a=((c=_.yj().browser)==null?void 0:c.toLowerCase())==="cobalt";var d;c=((d=_.yj().brand)==null?void 0:d.toLowerCase())==="samsung";d=a||b?void 0:()=>!1;b||a||!c||(d=yield d4b());b=g4b(b,a,d);h4b(b);i4b(b);return b}})},g4b=function(a,b,c){const d=a==="noncobalt";a=a==="cobalt"||a==="console"||d;return new k4b({ZD:a||
!b||!!c,jk:d||!a&&!b,gy:c})},f4b=function(a){a==="console"&&(speechSynthesis.cancel=()=>{console.log("__SPEECH_SYNTHESIS_CANCEL__")},speechSynthesis.speak=b=>{console.log(b.text)})};var l4b={button:!0,cell:!0,checkbox:!0,columnheader:!0,directory:!0,gridcell:!0,heading:!0,link:!0,listitem:!0,menuitem:!0,menuitemcheckbox:!0,menuitemradio:!0,option:!0,radio:!0,row:!0,rowgroup:!0,rowheader:!0,section:!0,sectionhead:!0,"switch":!0,tab:!0,tooltip:!0,tree:!0,treeitem:!0,alert:!0},m4b=function(a,b){if(a instanceof Element){var c=X4(a,"role");switch(c){case "checkbox":b.push("checkbox");a=X4(a,"aria-checked");a==="true"?b.push("checked"):a==="false"&&b.push("not checked");break;case "button":a=
X4(a,"aria-pressed");b.push(a?"toggle button":"button");a==="true"?b.push("pressed"):a==="false"?b.push("unpressed"):a==="mixed"&&b.push("partially pressed");break;case "tab":b.push("tab");a=X4(a,"aria-selected");a==="true"?b.push("selected"):a==="false"&&b.push("not selected");break;case "grid":case "main":case "option":case "region":case "row":b.push(c);break;case "menuitem":b.push("menu item");break;case "radio":b.push("radio button")}}},b5=function(a,b){const c=b.node,d=b.Qu,e=b.zn,f=b.EU,g=b.nG;
if(b.Tr&&c&&c.nodeName==="#text"&&(d||!a5(a,c))){var h;(a=(h=c.textContent)==null?void 0:h.trim())&&e.push(a)}else c instanceof Element&&(h=X4(c,"role"),h==="dialog"&&e.push("entering, dialog"),n4b(a,b),!(h==="main"||h==="grid"||e&&e.length!==0)||g||f.has(c)||(f.add(c),m4b(c,e)))},p4b=function(a,b,c={}){const d=c.dQ,e=[];var f=a.j===b;const g={node:b,Qu:!1,jC:!1,Tr:!0,TR:[],zn:e,EU:new Set,nG:!!c.nG};if(!c.mG&&!d&&!f){var h;a:{c=a.j;f=o4b(c);var k=o4b(b);if(f!==-1&&k!==-1){f-=k;k=c;var m=b;f<0&&(k=
b,m=c,f=-f);for(;f--;)k=(h=k)==null?void 0:h.parentElement;for(;k&&m;){if(k===m){h=k;break a}k=k.parentElement;m=m.parentElement}}h=null}if(h!==a.j){f=a.j;c=g.zn;f=f?f.parentElement:null;k=[];for(m=!1;f&&f!==h;){var n=X4(f,"role");if(n==="dialog"){k.unshift(n);a.A=!1;m=!0;break}n==="main"&&(m=!0);if(n){var q=[];n=Object.assign({},g,{node:f,Qu:!1,jC:!0,Tr:l4b[n],zn:q});b5(a,n);q.length!==0&&(q=Y4(q))&&k.unshift(q)}f=f.parentElement}!f&&a.A&&(k.unshift("dialog"),a.A=!1,m=!0);m&&(k.unshift("exit"),c.push(Y4(k)))}c=
e.length;if(h!==b){k=g.node;f=g.zn;k=k?k.parentElement:null;m=!1;for(q=[];k&&k!==h;){if(n=X4(k,"role")){var v=[];const w=Object.assign({},g,{node:k,Qu:!1,jC:!0,Tr:l4b[n],zn:v});b5(a,w);v.length!==0&&(v=Y4(v))&&q.unshift(v);n==="dialog"&&(m=!0)}k=k.parentElement}m&&(q.unshift("entering, dialog"),a.A=!0);q.length!==0&&(h=Y4(q))&&f.push(h)}c&&e.length>c&&(h=e[c],"exit, dialog"===e[c-1]&&h.includes("entering, dialog")&&e.splice(c-1,1));a.j=b}d?m4b(b,e):b5(a,g);return Y4(e)},o4b=function(a){let b=-1;for(;a;)++b,
a=a.parentElement;return b},a5=function(a,b){return b?b instanceof Element?X4(b,"aria-hidden")==="true"?!0:a5(a,b.parentElement):a5(a,b.parentElement):!1},n4b=function(a,b){var c=b.node,d=b.jC;const e=b.Tr,f=b.zn,g=b.TR;if(c instanceof Element&&(b.Qu||!a5(a,c))){var h=X4(c,"aria-labelledby");if(!q4b(a,h,b)&&(h=X4(c,"aria-describedby"),!q4b(a,h,b))){var k=X4(c,"id");h=()=>{};k&&(g.push(k),h=()=>{g.pop()});if(!(r4b(c,f)||(k=X4(c,"role"),k!=="presentation"&&s4b(c,f)||d))){c=c.childNodes;for(let m=0,
n=c.length;m<n;++m)d=Object.assign({},b,{node:c[m],Tr:e&&(!k||l4b[k])}),b5(a,d)}h()}}},q4b=function(a,b,c){const d=c.node,e=c.TR,f=c.zn;if(!b||!d)return!1;var g="";d instanceof Element&&(g=X4(d,"id")||"");if(e.includes(g))return!1;e.push(g);g=f.length;b=b.split(/\s+/);for(let k=0,m=b.length;k<m;++k){var h=b[k];let n;const q=(n=d.ownerDocument)==null?void 0:n.getElementById(h);q&&(h=Object.assign({},c,{node:q,Qu:!0,jC:!1,Tr:!0}),b5(a,h))}e.pop();return g!==f.length},r4b=function(a,b){return(a=X4(a,
"aria-label"))?(b.push(a),!0):!1},s4b=function(a,b){return a.nodeName.toLowerCase()==="img"&&(a=X4(a,"alt"))?(b.push(a),!0):!1},t4b=class{constructor(){this.j=null;this.A=!1}};var u4b=new Set(["aria-checked","aria-pressed","aria-selected"]),v4b=new Set(["aria-label","aria-labelledby","aria-describedby"]),d5=function(a){c5(a);if(a.jk){for(let b=100;b<350;b+=100)setTimeout(()=>{c5(a)},b);setTimeout(()=>{c5(a)},350)}},z4b=function(a,b){a.j()?(w4b(a,b),a.K="",a.ga="",a.G=b.target,x4b(a),a.jk&&(a.ea=!1,setTimeout(()=>{a.ea=!0},2E3)),Z4(()=>{if(document.activeElement&&b.target===document.activeElement&&!document.activeElement.querySelector(".zylon-focus")){a.Ba=new Set;const c=
document.querySelectorAll("[role=alert]"),d=new Set;for(let e=0;e<c.length;e++){const f=c[e];a.isVisible(f)&&(a.Yb.has(f)||a.B(f,{mG:!0}),d.add(f))}a.Yb=d;a.B(document.activeElement,{Xu:!0})}})):y4b(a)},h4b=function(a){var b=document.body;a.ta&&b.addEventListener("focusin",c=>{z4b(a,c)})},x4b=function(a){if(a.j()&&!a.A){a.A=a.UO(a.Bj,b=>{a.F=new Set;A4b(a,b)});for(const b of a.Ra)B4b(a,b)}},B4b=function(a,b){a.A&&a.A.observe(b,{childList:!0,attributes:!0,characterData:!0,subtree:!0,attributeOldValue:!0,
characterDataOldValue:!0,attributeFilter:"role aria-live aria-checked aria-pressed aria-selected aria-label aria-labelledby aria-describedby".split(" ")})},i4b=function(a){var b=document.body;a.ta&&(a.Ra.push(b),x4b(a),B4b(a,b))},C4b=function(a){clearTimeout(a.na);clearInterval(a.pb);a.na=0;a.J=[]},w4b=function(a,b){b=$3b(b.target,a.G);const c=a.K===a.ga;if(!b&&a.G||!a.K&&c)a.J.length&&C4b(a),d5(a)},A4b=function(a,b){a.j()&&b&&Z4(()=>{const c=document.activeElement;Z4(()=>{Z4(()=>{if(c===document.activeElement||
$3b(document.activeElement,c))for(const g of b)if(g.target===document.activeElement&&v4b.has(g.attributeName||"")){var d=a,e=g,f={dQ:!1};$4(e.target,d.F)||D4b(d,e)&&d.B(e.target,f)}else if(g.target===document.activeElement&&u4b.has(g.attributeName||""))d=a,e=g,f={dQ:!0},$4(e.target,d.F)||D4b(d,e)&&d.B(e.target,f);else if(g.type==="attributes"||g.type==="characterData")E4b(a,g.target);else if(g.addedNodes.length)for(d=a,e=g.addedNodes,f=0;f<e.length;f++){const h=e[f];E4b(d,h);!$4(h,d.F)&&h instanceof
Element&&d.eb(h)}})})})},y4b=function(a){a.A&&(a.A.disconnect(),a.A=null)},F4b=function(a,b){if(!b)return null;if(b instanceof Element){const c=X4(b,"aria-live");if(c!==null&&c!==void 0)return c==="off"?null:c;if(X4(b,"role")==="alert")return"assertive"}return F4b(a,b.parentElement)},E4b=function(a,b){F4b(a,b)&&!$4(b,a.F)&&a.isVisible(b)&&!G4b(a,b)&&(b instanceof Element||(b=b.parentElement||b),a.B(b,{mG:!0}))},D4b=function(a,b){if(!(b.target instanceof Element&&b.attributeName))return!1;var c;const d=
((c=b.oldValue)==null?void 0:c.trim())||"undefined";c=X4(b.target,b.attributeName)||"undefined";if(d==="undefined"||c==="undefined")return!1;if(c!==a.ga)return a.jk&&b.attributeName==="aria-label"?!d.includes(c)&&!c.includes(d):d!==c},G4b=function(a,b){return b?b instanceof Element&&X4(b,"role")==="alert"?!0:G4b(a,b.parentElement):!1},J4b=function(a,b){if(a.K||a.ea){var c=a.J;c.length&&C4b(a);setTimeout(()=>{c.length&&H4b(a,c);e5(a,b)},350)}else a.J.push(b),I4b(a)},e5=function(a,b){a.U&&(b=new a.U(b),
a.Bj.speechSynthesis.speak(b))},f5=function(a,b){return typeof b==="string"?b:p4b(a.Db,b,{nG:!0,mG:!0})},c5=function(a){a.jk&&a.Ga&&a.Bj.speechSynthesis.speak(a.Ga);a.Bj.speechSynthesis.cancel()},H4b=function(a,b){for(let c=0;c<b.length;++c)e5(a,b[c])},I4b=function(a){a.na||(a.pb=setInterval(()=>{c5(a)},100),a.na=setTimeout(()=>{H4b(a,a.J);C4b(a)},2E3))},k4b=class{constructor(a={}){this.Db=new t4b;this.F=new Set;this.Ba=new Set;this.ga=this.K="";this.gy=()=>!0;this.J=[];this.pb=this.na=0;this.fa=
[];this.X=[];this.V=new Map;this.ea=!1;this.Ra=[];this.G=this.A=null;const b=a.UO,c=a.ZD,d=a.jk,e=a.gy;this.Bj=a.Bj||window;this.UO=b||X3b;this.ZD=!!c;this.jk=!!d;e&&(this.gy=e);this.Yb=new Set;let f;this.h5vcc=!c||((f=this.Bj.h5vcc)==null?0:f.accessibility)?this.Bj.h5vcc:{accessibility:{textToSpeech:!0,builtInScreenReader:!1,highContrastText:!1}};a=this.Bj;this.Ga=(this.U=a.SpeechSynthesisUtterance||a.webkitSpeechSynthesisUtterance||a.mozSpeechSynthesisUtterance||a.oSpeechSynthesisUtterance||a.msSpeechSynthesisUtterance)?
new this.U(", a"):null;let g,h,k;this.Wc=(((g=this.Bj)==null?void 0:(h=g.navigator)==null?void 0:(k=h.userAgent)==null?void 0:k.toLocaleLowerCase())||"").includes("cobalt");let m;if(this.ta=!((m=this.Bj)==null||!m.speechSynthesis)&&!!this.U){let n,q;if((n=this.h5vcc)==null?0:(q=n.accessibility)==null?0:q.builtInScreenReader)this.h5vcc.accessibility.builtInScreenReader=!1,window.addEventListener("unload",()=>{d5(this)}),window.addEventListener("beforeunload",()=>{d5(this)})}}j(){if(document.renderPostponed)var a=
!1;else if(this.ZD)a=this.gy();else if(a=this.Wc){let b,c;a=!!((b=this.h5vcc)==null?0:(c=b.accessibility)==null?0:c.textToSpeech)}return a}eb(a){a=a.querySelectorAll("[aria-live]");for(let b=0;b<a.length;++b)E4b(this,a[b])}isVisible(a){if(!a)return!1;if(a===document.body)return!0;if(a instanceof Element){const b=window.getComputedStyle(a);if(b.display==="none"||b.visibility==="hidden"||b.opacity==="0"&&b.transitionDuration==="0s")return!1}return this.isVisible(a.parentElement)}B(a,b){if(this.j()&&
a){var c=p4b(this.Db,a,b);if(c){($4(a,this.Ba)&&F4b(this,a)==="assertive"||this.ea)&&d5(this);Z3b(a,this.F);Z3b(a,this.Ba);this.ga=c;a===document.activeElement&&(this.K=c,(b==null?0:b.Xu)&&!this.G&&(this.G=a));this.jk&&a instanceof Element&&(b==null?0:b.Xu)&&Y3b(a,c);a=[];(b==null?0:b.Xu)&&this.fa.length&&(a.push(this.fa.join(", ")),this.fa=[]);a.push(c);if(b==null?0:b.Xu)this.X.length&&(a.push(this.X.join(", ")),this.X=[]),this.V.size&&(a.push(Array.from(this.V.values()).join(", ")),this.V.clear());
b=a.join(", ");this.jk?J4b(this,b):e5(this,b)}else this.jk&&a===document.activeElement&&d5(this)}}La(a,b){if(this.j()&&a&&(a=f5(this,a))){if(b==null?0:b.DY)a=a.toLowerCase();(b==null?0:b.iT)&&c5(this);e5(this,a)}}Jc(a){var b=this.fa;this.j()&&a&&(a=f5(this,a))&&b.push(a)}Fc(a,b){if(b){var c=this.V;this.j()&&a&&(a=f5(this,a))&&c.set(b,a)}else b=this.X,this.j()&&a&&(a=f5(this,a))&&b.push(a)}};var a4b=()=>!1,e4b=_.gDa;_.R(_.xHa,()=>j4b);
_.r();
}catch(e){_._DumpException(e)}
})(this._yttv);
// Google Inc.
