_F_installCss(".ytLrGenericPromoRendererHost{display:block;padding-top:2rem;margin-left:4.5rem;text-align:center;width:73.5rem}.ytLrGenericPromoRendererButton{display:inline-block}.ytLrGenericPromoRendererText{height:9.5rem;position:relative;padding-top:8.5rem}.ytLrGenericPromoRendererShorts .ytLrGenericPromoRendererText{height:5.25rem}.ytLrGenericPromoRendererTitle{font-family:YTSans,Roboto,Noto Sans CJK ZH-HK,Noto Sans Thai,Arial,Helvetica,sans-serif;font-size:2.5rem;font-weight:400;line-height:3rem;font-weight:700;color:#f1f1f1;display:block;text-align:center;white-space:pre-wrap}.ytLrGenericPromoRendererGhostBoxContainer{position:absolute;z-index:-1;width:74.5rem;overflow:hidden;white-space:nowrap}.ytLrGenericPromoRendererTile{display:inline-block!important;margin-right:1.5rem}.ytLrGenericPromoRendererForegroundImage{height:10.25rem;margin-bottom:2.375rem;margin-top:8.5rem}.ytLrGenericPromoRendererShorts .ytLrGenericPromoRendererForegroundImage{height:4.375rem;margin-bottom:2.25rem;margin-top:12.625rem}.ytLrGenericPromoRendererBodyText{font-family:Roboto,Noto Sans CJK ZH-HK,Noto Sans Thai,Arial,Helvetica,sans-serif;font-size:1.25rem;line-height:1.75rem;font-weight:400;color:#aaa;display:block;margin-top:.5rem;text-align:center}.ytLrGenericPromoRendererPlaceholderTiles{background-position:3rem 0;background-repeat:no-repeat;background-size:65.5rem 13.5rem}.ytLrGenericPromoRendererPlaceholderTiles::before{content:\"\";display:inline-block;height:100%;width:100%;background-image:linear-gradient(0deg,rgba(15,15,15,1) 0,rgba(15,15,15,.869037) 11.87%,rgba(15,15,15,.756106) 21.53%,rgba(15,15,15,.659165) 29.34%,rgba(15,15,15,.576173) 35.61%,rgba(15,15,15,.505087) 40.7%,rgba(15,15,15,.443868) 44.93%,rgba(15,15,15,.390473) 48.65%,rgba(15,15,15,.34286) 52.18%,rgba(15,15,15,.298989) 55.86%,rgba(15,15,15,.256817) 60.03%,rgba(15,15,15,.214304) 65.03%,rgba(15,15,15,.169407) 71.19%,rgba(15,15,15,.120085) 78.85%,rgba(15,15,15,.0642963) 88.34%,rgba(15,15,15,0) 100%);left:1.375rem;width:78.625rem;height:13.5rem;position:absolute}.ytLrGenericPromoRendererInline{background-position:0 0;margin-top:.5rem}.ytLrGenericPromoRendererForeground .ytLrGenericPromoRendererText{padding-top:0}.ytLrGenericPromoRendererEntity{position:absolute;transform:translateY(-50%);top:50%;margin:0;padding:0;width:100%}.ytLrGenericPromoRendererEntity .ytLrGenericPromoRendererText{height:auto;padding-top:0}.ytLrGenericPromoRendererEntity .ytLrGenericPromoRendererButton{display:block;margin-top:4.5rem}.ytLrGenericPromoRendererShelf{margin-left:6.5rem}.ytLrGenericPromoRendererShelf.ytLrGenericPromoRendererPlaceholderTiles::before{width:81rem}sentinel{}");
this._yttv=this._yttv||{};(function(_){var window=this;
try{
var sYb=function({data:{title:a,bodyText:b,actionButton:c,foregroundImage:d},inline:e,entity:f,type:g=2}){let h;return _.E("host",{className:{ytLrGenericPromoRendererEntity:f,ytLrGenericPromoRendererForeground:!!d,ytLrGenericPromoRendererInline:e,ytLrGenericPromoRendererPlaceholderTiles:!f&&!d,ytLrGenericPromoRendererShelf:g===0,ytLrGenericPromoRendererShorts:!!_.u(c==null?void 0:(h=c.buttonRenderer)==null?void 0:h.command,_.fp)}},_.I(d,k=>_.E(_.gJ,{className:"ytLrGenericPromoRendererForegroundImage",
jc:"contain",data:k,idomKey:"ytLrGenericPromoRendererForegroundImage",Ed:!1,width:26}),()=>_.E("div",{className:"ytLrGenericPromoRendererGhostBoxContainer"},f?null:g===0?_.E(_.nm,null,_.SH(_.HX(4),k=>_.E(_.IX,{idomKey:`${"ytLrGenericPromoRendererTile"}-${k}`,borderRadius:.6875,className:"ytLrGenericPromoRendererTile",height:13.375,width:22}))):g===1?_.E(_.nm,null,_.SH(_.HX(5),k=>_.E(_.IX,{idomKey:`${"ytLrGenericPromoRendererTile"}-${k}`,borderRadius:.6875,className:"ytLrGenericPromoRendererTile",
height:13.375,width:12.375}))):_.E(_.nm,null,_.SH(_.HX(3),k=>_.E(_.IX,{idomKey:`${"ytLrGenericPromoRendererTile"}-${k}`,borderRadius:.6875,className:"ytLrGenericPromoRendererTile",height:13.375,width:22}))))),_.E("div",{className:"ytLrGenericPromoRendererText",id:e?_.JB[5]:void 0,"aria-live":e?"off":"polite",idomKey:"ytLrGenericPromoRendererText"},_.E(_.V,{className:"ytLrGenericPromoRendererTitle",data:a}),_.E(_.V,{className:"ytLrGenericPromoRendererBodyText",data:b})),_.dI({renderer:c,config:this.xb()}))};var tYb=class extends _.U{constructor(){super(...arguments);this.template=sYb;this.P=_.Wp.getInstance();this.cb=_.B.get(_.mC);this.xb=()=>{const a={className:"ytLrGenericPromoRendererButton",focused:this.props.focused,Ja:!1,preventAutoToggle:!0,idomKey:"ytLrGenericPromoRendererButton"};return{buttonRenderer:{component:_.PJ,props:Object.assign({},a,{shape:3})},toggleButtonRenderer:{component:_.UK,props:Object.assign({},a,{shape:3})}}}}Y(){_.T(this,_.L(this.P,new _.J("tts"),this,()=>{this.props.inline&&
_.iC(this.cb,this.el)}))}};tYb.S="ytlr-generic-promo-renderer";tYb.T="ytLrGenericPromoRendererHost";_.Q(_.SM,tYb);
}catch(e){_._DumpException(e)}
try{
_.p("zKSK7");

_.r();
}catch(e){_._DumpException(e)}
})(this._yttv);
// Google Inc.
